### ISSUE TITLE
Oddaja projekta 

### ISSUE THREAD

**Issue by sarazuzek** [sarazuzek/Pomocnik-za-trgovanje#2]

**Comment by majbc1999** [comment]
Živjo,

takoj ko zaženem projekt, mi izpiše `Template 'prijava.html' not found.` Problem je v tem, da imate template v mapici `VIEWS`, ki pa jo Ubuntu ne prepozna. Treba bo spremeniti ime v `views` z malimi črkami, da bo delovalo v vseh operacijskih sistemih.

Zaenkrat mi registracija prav tako ne deluje. Za vsake podatke mi izpiše:
```
Registracija ni možna, to uporabniško ime že obstaja.
```

Tako preostanek projekta nisem mogel pregledati.

Pred oddajo bo treba projekt usposobiti še v Binderju (glej [vzorčni projekt](https://github.com/jaanos/OPB-bottle)). Link dodajte v `README.md` (podobno kot v prej omenjenem vzorčnem projektu).

**Comment by alanmarinic** [comment]
Živjo,
hvala za opozorilo. Sva odpravila vse napake. 
Edini znani bug je da včasih ko klikneš na gumb s povezavo te ne preusmeri le nalaga dlje časa, temveč ko klikneš drugič pa te hitro preusmeri.

Spodaj navajam podatke za uporabnika z nekaj vnešenimi trejdi, tako da boste lažje testirali aplikacijo.
**username:** `avto`
**password:** `avto123`

Žal pa nama binderja ni uspelo usposobiti, čeprav sem naredil enako kot je prof. vedno izpiše:
```
500: Internal Server Error
```
Mapo binder in povezavo sva vseeno za zdaj pustila. Če je možno bi ga kljub temu oddala, saj se nama program zaganja brez težav.
