### ISSUE TITLE
Oddaja

### ISSUE THREAD

**Issue by alanmarinic** [sarazuzek/Pomocnik-za-trgovanje#3]
Živjo,
hvala za opozorilo. Sva odpravila vse napake. 
Edini znani bug je da včasih ko klikneš na gumb s povezavo te ne preusmeri le nalaga dlje časa, temveč ko klikneš drugič pa te hitro preusmeri.

Spodaj navajam podatke za uporabnika z nekaj vnešenimi trejdi, tako da boste lažje testirali aplikacijo.
**username:** `avto`
**password:** `avto123`

Žal pa nama binderja ni uspelo usposobiti, čeprav sem naredil enako kot je prof. vedno izpiše:
```
500: Internal Server Error
```
Mapo binder in povezavo sva vseeno za zdaj pustila. Če je možno bi ga kljub temu oddala, saj se nama program zaganja brez težav.

_Originally posted by @alanmarinic in https://github.com/sarazuzek/Pomocnik-za-trgovanje/issues/2#issuecomment-1574926925_

**Comment by majbc1999** [comment]
Živjo, 

ponavadi je dobro, da je Binder delujoč pred zagovorom (saj potem tudi profesorju aplikacije ni treba lokalno zaganjati). 

Potem ko sem malo pregledoval kodo vajinega projekta, sem opazil, da skoraj povsod za vse preusmeritve uporabljata kar pot (in ne funkcije `url`). Verjetno je to problem nedelujočega Binderja. 

Torej, v primeru
```html
<form action="/buy_sell" method="post">
```
bo potrebno povsod spremeniti na
```html
<form action="{{url('buy_sell')}}" method="post">
```

Tudi v `trgovanje.py` je potrebno usposobiti redirectanje na podoben način. Torej, npr. v kodi

```python
redirect(f'/{user_id}/index')
```
 uporabita funkcijo `url`:

```python
redirect(url('index', id=user_id))
```

Asistent bo danes tudi objavil navodila, kako usposobiti Binder (čeprav mislim, da imata na repozitoriju ustrezne datoteke in je problem samo v funkciji `url`). Pazita, da funkciji `url` kot parameter pošiljata ime funkcije iz `trgovanje.py` in ne samo poti. To je namreč prav tako povzročalo težave z Binderjem v prejšnjih letih.

**Comment by alanmarinic** [comment]
Zivjo, 
povsod sem spremenil path -> url, enako za redirect, a binder še vedno vrne enak error.

**Comment by majbc1999** [comment]
Živjo,

najprej se opravičujem, da nisem odpisal že prej. Veliko sem poskušal usposobiti Binder, ampak tudi meni ni uspelo. Bom napisal še asistentu @gasperxy, naj pogleda na hitro, sicer pa boste lahko oddali tudi brez Binderja.

Projekt sem sedaj v celoti pregledal in načeloma deluje super. Potrebno bo sicer popraviti samo še nekaj malenkosti. 

1. poti v datoteki `graphs.py` morajo biti z malimi črkami (tako kot se mape dejansko imenujejo). Torej, `fig.write_html('Views/Graphs/assets.html')` ne deluje, treba bo narediti `fig.write_html('views/graphs/assets.html')`.
2. ko izbiram možnost z drop-down listom (na primer tip trade-a v `Dodaj trade`, se mi ne izpiše izbrana opcija).

Ko popravita te dve malenkosti mi sporočita, da še zadnjič pregledam (in odobrim) projekt.

**Comment by alanmarinic** [comment]
Živjo,
spet hvala za pomoč in popravke!

Poti v `graphs.py` sva popravila.

Glede popravka drop-down izbir, če sem prav razumel, se v `Dodaj trade` izbira ustrezno prikaže, kot na priloženi sliki. 

<img width="895" alt="Screenshot 2023-06-09 at 19 01 46" src="https://github.com/sarazuzek/Pomocnik-za-trgovanje/assets/56591381/513132e4-db15-4aea-a78c-8994373d7775">

Edino kjer izbira ni bila prikazana je v `Statistika` in `Analiza`.

To sva popravila tako da spodaj in v drop-down meniju izpiše izbrano strategijo. Kot na sliki:

<img width="1185" alt="Screenshot 2023-06-09 at 19 41 05" src="https://github.com/sarazuzek/Pomocnik-za-trgovanje/assets/56591381/41d09f0a-b8c3-4c7a-8eec-d70afd627e7f">


Če ste imeli v mislih kaj drugega prosim povejte da popraviva

**Comment by majbc1999** [comment]
Živjo, 

zaenkrat mi tako pokaže:
![image](https://github.com/sarazuzek/Pomocnik-za-trgovanje/assets/49946994/bbf2a4b0-5635-4490-be63-040cdfe266d2)

Ko kliknem sicer lahko izberem, vendar po kliku izbira spet izgine:
![image](https://github.com/sarazuzek/Pomocnik-za-trgovanje/assets/49946994/44b3d558-316e-4803-bc5f-f70613a1a317)

Sem pogledal, če je morda problem brskalnik Chrome, ampak v Firefoxu naletim na isti problem. V katerem brskalniku in sistemu tebi deluje?

**Comment by alanmarinic** [comment]
Zivjo, 
nama dela v Safariju, ampak pri drugih se pa res ne prikaže kot bi moralo, bova poskusila popraviti

**Comment by alanmarinic** [comment]
Popravljeno, sedaj bi moralo delati:)

**Comment by majbc1999** [comment]
Super, počakajmo še asistenta kakšen dan, če ima kakšno rešitev za Binder, potem pa se lahko zmenite s profesorjem za zagovor.

**Comment by gasperxy** [comment]
Živjo,

Se opravičujem za pozen odgovor. Problem je pomoje v tem, da sta sicer uporabila okoljsko spremenljivko "POSTGRES_PORT", ampak je nista uporabila v razredu Repo, s katerim delata vse poizvedbe na bazo. Povezava iz binderja na bazo je tako potekala preko porta 5432, kar ni ok, ker to ne deluje v binderju (zato se je sprožil error).

Sem vama naredil pull request, kjer sem vama popravil, da bi sedaj moralo uporabit taprav port (če sta pogledala pri meni, sem imel tudi tako narejeno :)). Javita, če vama bo potem delalo.

**Comment by alanmarinic** [comment]
Dela!
Hvala obema za pomoč.
